---
- name: install Jenkins
  hosts: server1
  become: yes
  tasks:
  - name: update system
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: upgrade system
    apt: upgrade=dist force_apt_get=yes

  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes

  - name: Install Java 11
    apt:
      name: openjdk-11-jdk
      state: present
      update_cache: yes

  - name: Add Jenkins apt repository key
    ansible.builtin.get_url:
      url: "https://pkg.jenkins.io/debian{{ '-stable' if (jenkins_prefer_lts | bool) else '' }}/jenkins.io.key"
      dest: /etc/apt/trusted.gpg.d/jenkins.asc
      mode: '0644'
      force: true

  - name: Add Jenkins apt repository.
    apt_repository:
      repo: "https://pkg.jenkins.io/debian{{ '-stable' if (jenkins_prefer_lts | bool) else '' }} binary/"
      state: present
      update_cache: true

  - name: Install Jenkins
    apt:
      name: jenkins
      state: latest        
    
  - name: Install Nginx
    apt:
      name: nginx
      state: latest
        
